INSERT INTO SATELLITE (id, name, x, y)
VALUES (1, 'KENOBI', -500, -200);

INSERT INTO SATELLITE (id, name, x, y)
VALUES (2, 'SKYWALKER', 100, -100);

INSERT INTO SATELLITE (id, name, x, y)
VALUES (3, 'SATO', 500, 100);